; PlatformIO Project Configuration for libSLIPStream
; Supports both Arduino and ESP-IDF frameworks

[env:arduino]
platform = espressif32
framework = arduino

[env:espidf]
platform = espressif32
framework = espidf
